default_language_version:
  python: python3.10

repos:
# 'meta' repo for debugging pre-commit itself
#  - repo: meta
#    hooks:
#      - id: check-hooks-apply
#      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
      - id: black-jupyter
        args:
          - "--config"
          - "./pyproject.toml"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-file"
          - "./pyproject.toml"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length"
          - "88"
          - "--extend-exclude"
          - "[.github, .idea, .vs]"
          - "--extend-ignore"
          - "[E201, E202, E203, E731, W503]"

# Type-checking, security-checking, and testing via mypy, bandit, and pytest
# are expensive, so we leave them commented out but here so we can see their set-up.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args:
          - "--config-file"
          - "./pyproject.toml"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - "--configfile"
          - "./pyproject.toml"
          - "--recursive"
          - "-ll"
        additional_dependencies:
          - "bandit[toml]"

  - repo: local
    hooks:
      - id: pytest-py
        name: pytest-py
        entry: pytest
        language: system
        pass_filenames: false
        args:
          - "-v"
          - "-n"
          - "auto"

#  - repo: local
#    hooks:
#      - id: pytest-nb
#        name: pytest-nb
#        entry: pytest
#        language: system
#        pass_filenames: false
#        args:
#          - "--nbmake"
#          - "*/*/*.ipynb"
#          - "-n"
#          - "auto"
